### ISSUE TITLE
fix memory leaks

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#158]
The release notes say:

> Valgrind found three small memory leaks in the VT port (which would apply to all other ports as well). There are still more leaks in other ports, which should be addressed.

So this issue is about listing those leaks and the way the valgrind report was created (I _guess_ by running the demos with active valgrind memcheck).

**Comment by Bill-Gray** [comment]
Correct,  I ran Valgrind memcheck on a few demos for the VT,  X11,  and SDL2 ports.  I should say that the X11 and SDL2 ports left lots of memory unfreed at shutdown.  None of it was actually marked as "lost".  However,  it was not properly freed.

Fixing the leaks would require more knowledge of X11 or SDL2 than I have.  Also,  the issue should probably be addressed upstream in the @wmcbrine fork.

I also tried running Valgrind with the WinGUI port,  under Wine.  In theory,  you can do that (and as the Wine folks point out,  the ability to do so could be quite useful to Windows developers.)  I couldn't get it to work,  though.  Had I done so,  I'd have tested both the WinGUI and WinCon ports.

[Valgrind shows lots of unfreed memory in ncurses](https://invisible-island.net/ncurses/ncurses.faq.html#config_leaks),  but apparently,  this is a "won't fix except in debug mode" issue.

I am reasonably sure there's no way to get Valgrind to work for the DOS or OS/X ports.

**Comment by wmcbrine** [comment]
The design of curses is inherently "leaky", at least if you use it in the standard way, with an `initscr()` at the start and an `endwin()` at the end. `endwin()` *can't* deallocate anything, because curses is supposed to be able to resume from an `endwin()`. If you want to deallocate the memory, you need to explicitly call (the little-used) `delscreen()`.

All allocated memory is reclaimed by the operating system on process exit, so there's no reason to set `delscreen()` as at `atexit()` process or the like, other than to appease Valgrind.

If and only if you find memory still leaked after a `delscreen()` would I consider that a problem.

**Comment by GitMensch** [comment]
So should we close this issue or is there anything we can actually do concerning other ports than VT?

**Comment by Bill-Gray** [comment]
It's not hopeless.  Commit cb4344a163b38e6dfb7e was a start,  freeing up quite a bit of memory in the X11 port at shutdown.  There's quite a bit more that could be done,  though greater knowledge of SDLx and X11 might be required (I just did the easy bits,  and probably not all of them.)

**Comment by Bill-Gray** [comment]
I think I've fixed all the SDLn and X11 memory leaks that I can readily figure out.  The other ports all free memory cleanly.  When I have a curses program where I'm figuring out memory problems,  I just use any of those ports for the memory-debugging parts.  So I think we're done here.
