### ISSUE TITLE
ncurses-style init_extended_color(), init_extended_pair(), extended_color_content(), extended_pair_content() functions

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#159]
The release notes say:

> VT and WinGUI versions can now access 2^20 = over a million color pairs and 2^24+256 = 16777472 colors. This should be extended to SDLx and X11, and possibly WinCon.

So this issue is about adding the functionality to more ports.

**Comment by Bill-Gray** [comment]
Just a note that in addition to SDLx, WinCon and X11, DOSVGA can also access 'full' colors,  at least in 16-,  24-,  and 32-bit modes.  I don't know about Plan9.

Of these,  X11 would be my personal priority (simply because I rarely use the SDLs except to test them),  followed perhaps by DOSVGA (which has a "nifty" factor and,  I think,  may serve as the start of a more general cross-platform solution : one where we use PSF fonts instead of relying on platform-specific fonts.)  But if I'm the one doing it,  it'll probably be a while before I find the time to extend full-color functionality past VT and WinGUI.

**Comment by Bill-Gray** [comment]
Now added to SDLx and X11.  Still could do in WinCon,  DOSVGA and Plan9.  I may give it a shot sometime for WinCon;  probably won't for the the other two platforms,  and can't say it's much of a priority for WinCon.  (A Linux framebuffer port is a higher priority,  and would have full color baked into it from the get-go.)
