### ISSUE TITLE
A proper way to integrate visually in black-on-white environments?

### ISSUE THREAD

**Issue by staalmannen** [Bill-Gray/PDCursesMod#173]
Dear all,

PDCurses work really well on Plan9 but one thing that is bugging me is that it defaults to the white-on-black colors which look out of place in Plan9 where the default is a white background and black text (see screenshot: https://github.com/Bill-Gray/PDCurses/pull/172#issuecomment-651341811).

What is the proper way to make all PDCurses applications look "more native" in such an environment?

**Comment by GitMensch** [comment]
> What is the proper way to make all PDCurses applications look "more native" in such an environment?

Adjust the applications - really. If the application for example "draws" different areas and white, black and blue have a different meaning (the colors were explicit requested!) then there should be no "magic" changing the colors.

You _may_ could try to add an option, for example triggered with an environment variable - this may be useful for every port, therefore I suggest to have it in a different PR based on current master. Something along the following:

~~~
PDCURSES_COLORS
   I    invert all colors
   S    swap black and white -> invert all colors containing only those
~~~

You'd then check this environment variable during `initscr()` and if it is set internally adjust the color pairs when they are created.

**Comment by staalmannen** [comment]
Indeed having an environment variable (or compile-time switch) option to switch black and white would probably be the best. Inverting all colors might look strange I think? 

I like the idea of having this as a compile-time option which then potentially could "fix" all applications without having to change their code by simply adding something to the CFLAGS.

**Comment by Bill-Gray** [comment]
Curses does have a concept of 'default colors'.  To make use of it,  though,  you have to _not_ call `start_color()`,  and it only works at present in ncurses and the VT fork.  (Maybe in DOS and OS/2.)

Some time back,  while attempting to puzzle out how colors should work if you don't call `start_color()`,  or do so only after having displayed text,  or use an unitialized color,  I wrote [a bit of color testing code](https://www.projectpluto.com/temp/init_col.c) that may be of interest.  Much of what follows was derived from compiling and running this code with ncurses and assuming that that's the "desired" behavior;  the documentation I found was somewhat confusing,  and it was easier just to explore what actually happens:

- If you don't call `start_color()`at all,  or only call it after some text has been displayed,  text should appear in the default color.  If your xterm is white-on-blue,  your PDCurses or ncurses app will show everything in white on blue.
- Use an unitialized color pair,  and you'll get undefined results.  (In ncurses,  you get black on black text.  PDCurses uses green on yellow in hopes you'll look at it and realize that it's a color problem,  rather than thinking the text just isn't showing up.)
- WinCon has a default background,  but I don't think that gets used by PDCurses at present.  In theory,  all platforms could have default background and foreground colors,  but only a few actually do.  For WinGUI,  X11,  and the SDLs,  we'd probably have to just pick them at random.

**Comment by Bill-Gray** [comment]
On further reflection,  I've come up with and added commit b642c9127919 to enable this issue to be addressed.

As mentioned above,  there really is no particular guarantee,  as best I can tell,  as to what colors you'll get on a particular platform if you don't actually call `set_color()`.  Once you do,  you will get white text on a black background (until you start calling `init_pair()` and setting attributes accordingly).

To address the first issue,  you can,  within `PDC_scr_open()` for your platform,  insert the code
```
   SP->orig_attr = TRUE;    /* yes,  this platform has 'original attrs',  and they are... */
   SP->orig_fore = COLOR_BLACK;   /* black text on a white background */
   SP->orig_back = COLOR_WHITE;
```
Do that,  and a PDCurses program that never calls `set_color()` will show text in black with a white background (i.e.,  what you're looking for on Plan9).  That's been true all along,  before my most recent commit.

Commit b642c9127919 enables you to specify what colors should be used once `start_color()` You can now call `PDC_set_background_colors( COLOR_BLACK, COLOR_WHITE)` from within `PDC_scr_open()` to get the effect I believe you seek : namely,  under Plan9,  text will show up as black characters on a white background unless you start setting colors differently.

I've tested this out on WinGUI,  X11,  and VT just to verify that it works,  but I don't actually think any platform other than Plan9 really needs this.  Lacking a Plan9 system myself,  I'll leave it to you to add the relevant lines above and test it out.

**Comment by GitMensch** [comment]
@staalmannen Can you please recheck if there's anything we need to do about this for the PDCursesMod 4.2.1?
If I'm not wrong it is the only new feature for that version (mainly a bugfix release in any case) so far, as long as @Bill-Gray doesn't include https://github.com/wmcbrine/PDCurses/pull/102 here before and I'd like to know if this is a feature to be said to be "in development" or "working".

**Comment by staalmannen** [comment]
Sure I will check it as soon as I have time because this would be a great improvement.

**Comment by Bill-Gray** [comment]
I've since tested this fix (by temporarily telling various ports that they had,  say,  a default red background and purple foreground) and it seems to work.
