### ISSUE TITLE
own project name to remove confusion with upstream, remove of fork status

### ISSUE THREAD

**Issue by loblolly986** [Bill-Gray/PDCursesMod#177]
At present, there are two projects named "PDCurses":

- The original, official one, maintained by William McBrine;
- This one, maintained by Bill Gray, originally forked during a lengthy dormancy of the official project.

I understand that proposals have been made over the years to merge this fork, with its various changes and improvements, into the official project, but to little avail due to disagreement between the maintainers over some of the changes, so expectations are that the two will remain divergent for the foreseeable future.

It seems obvious to me that this project should adopt a name of its own to distinguish it from the original project. It might not have been a big deal at one time, but it's pretty clear that at this point this is no longer merely a "fork" in the limited sense common on GitHub (one's personal copy of a repo in which to make changes or tweaks here or there, ideally for merging into the official one), but a "fork" in the sense of a full-blown divergent project; and the official PDCurses project is no longer inactive. Having two projects with the same name is an obvious source of confusion.

My suggestion is "PDCursesEx" (or alternatively, "PDCurses-Ex"). It's short, it conveys that this is a variant of PDCurses, and it specifically conveys that it is an "extended" variant offering additional features - the "Ex" being a familiar suffix in programming in names of functions that offer "extended" capabilities or flexibility over the "regular" version.

Compare with any number of examples of other split/derivative projects (forks) that have adopted some degree of name change to distinguish themselves. A handful off the top of my head: MinGW vs. MinGW-w64; OpenOffice vs. LibreOffice; Firefox vs. Pale Moon; DivX vs. Xvid; Media Player Classic vs. Media Player Classic - Home Cinema.

When referring to this project in a discussion, I'd want to be able to use something simple like "PDCursesEx", rather than having to use such verbiage as "Bill-Gray's fork of PDCurses".

Modifying the name does not mean we have to replace every reference to "PDCurses" in the code; I'm thinking primarily the repository name, documentation, the string provided in `ttytype`, and the version resource used in Windows DLL builds. Perhaps also the DLL name (e.g. pdcursesex.dll or pdcurses-ex.dll), unless this would cause compatibility problems. Nor would it mean we would need to restart the version numbering. It also does not have to mean abandoning any possibility of a future merge with official PDCurses, if Mr. McBrine eventually so desires; at minimum, it would simply disambiguate the projects for the time being.

**Comment by GitMensch** [comment]
It is not my repository so I won't decide what is happening but I don't see the need (and would feel a bit uneasy with any rename).
We currently have PDCurses3 and PDCurses4, that's perfectly fine to me.
IF @Bill-Gray has a different point of view he'll reopen this and is the one to do the actual changes.

**Comment by loblolly986** [comment]
Version numbering isn't adequate for disambiguation, particularly since official PDCurses is no longer an inactive project at this time (and under no ethical obligation to stick with 3.x version numbering or generally make concessions just to accommodate this project); the version number is not part of the name per se. If I thought otherwise, I wouldn't have opened this (and I have seen the ideas discussed in other issues involving arranging with William that the official project stay with 3.x or use odd-numbered versioning, ideas I disagree with for the aforementioned reasons). I do await @Bill-Gray's opinion (maybe @wmcbrine's also?), but also think perhaps it was premature to close this (!) (as if it was a non-issue) before he's even had a say.

I would agree with sentiments expressed elsewhere that the ideal solution would be for some sort of merger of the two projects into one "PDCurses" to take place, but it doesn't look like that's going to happen any time soon, if ever.

**Comment by GitMensch** [comment]
It was closed because so far it looked like both maintainers will stick with the 3.x/4.x for separation (and while it isn't an ideal match - python2/python3 were only separated that way, too).

**Comment by wmcbrine** [comment]
No Simon, that was your idea. I never agreed to that, and in fact I've found the suggestion absurd. I was going to bring this naming issue up myself, but it seemed to belabor the obvious, and I was trying to be polite...

For the record, "official" PDCurses was never quite an "inactive" project -- granted, there were no "releases" for ten years, but there were updates to the repository in most of those years. In that era, I converted the repository to Git. I created pdcurses.org. And I continued to post to the mailing list. It was, frankly, presumptuous to lay claim to "PDCurses 4", as though I weren't even there at the time. I was. Perhaps I should've objected sooner. But perhaps you should have asked.

Also for the record: As far as I'm concerned, there is no such thing as PDCurses 4. And this fork is not the "future" of "official" PDCurses. I have more sense than to add to the confusion by stepping on your version numbers, so I'll skip that, but I'm certainly not sticking with 3.x forever.

If you're going to continue with releases, I'd suggest a name something like "PDCurses-bg", or even "BGCurses". I'm not really comfortable with he implication that it's simply "enhanced" or "extended" PDCurses. I consider it a set of enhancements (which I do hope to adopt), alongside other things I consider misfeatures, and some neutral differences (matters of taste).

**Comment by GitMensch** [comment]
Ok, @wmcbrine I thought you'd have spoken up with the 3.x suggestion if this would not be something you would like to do.
Given that this is *not* the way to go I also highly suggest to rename the project; renaming the repo should be possible by asking the GH support; it would also be possible to remove the "fork" status, which I'm not sure it would be good or not (at least it would add some "features" here like the currently not working search".

I have the same feeling about "ex" as William but would also have a similar feeling about "bg" (if the original would have the name WilliamsPDCurses I'd have lost interest to that, even if it may not be something "logical").
It is too much "PDCurses" to change that bit (or at least I feel uneasy about that) , maybe PDCursesX?

Note: I'd prefer to have this handled before the "coming-very-soon-now" release.
@wmcbrine Do you have a suggestion what to change? I'd just adjust the repo name, the README and the ttytype name...

@Bill-Gray Are you fine with this? Can you drop GH support a request for name change and possibly also remove of fork status?

**Comment by Bill-Gray** [comment]
I'm fine with a name change.  As you all point out for different reasons,  just relying on the version number as a differentiator wasn't a very good solution.  (In my defense,  the only alternative I saw was changing the project name,  which seemed like a big step at the time.  It's less so now.)

I agree with @GitMensch that this fork is "too much PDCurses" to leave that out of the name,  and would be inclined to go with PDCursesX,  where the 'X' just means "it's different from PDCurses".  I'm not so much concerned with what the name means as I am with ensuring that there's minimal confusion.  

I am perfectly happy with the status of this as a fork (because let's face it,  that's what it is... a rather drastic fork,  but the family heritage is clear.)  I don't think we can change the name without losing that bit,  though.  Not a big deal;  the HISTORY file and documentation in general can make the relationship clear.

Which leaves the question of what exactly changes.  At bare minimum,  I'd want the repository to be located at https://github.com/Bill-Gray/PDCursesX (or whatever name we settle on),  and for that name to appear throughout the documentation.  As Simon suggests, `ttyname` ought to get the name change as well.  I'm in no rush to have `pdcurses.dll` become `pdcursesx.dll`;  if you're using both this library and William's,  you'd have to come up with some other way of disambiguating them.

I share Simon's thought that if we're going to do this (and it seems we're converging on agreement there),  it should be done relatively soon,  before the "imminent release".  Since @loblolly986's suggestion is a mere eleven hours old as I write this,  I'll certainly wait a bit for comments... I kinda have to do that anyway;  the day job calls today.

**Comment by GitMensch** [comment]
As noted: @Bill-Gray you can ask the GH staff to change the name and remove the fork status - this way we keep the history and all issues and every else but the "is 800 commits ahead, 600 commits behind" and get a search feature.

**Comment by loblolly986** [comment]
@wmcbrine: Funnily enough, "PDCurses-BG" and "BGCurses" were the first two ideas I came up with also (with preference to the former, as I'm inclined to agree with Bill and Simon that this project is "too much PDCurses" to leave that out). I ended up settling on suggesting "PDCursesEx" because it seemed a more descriptive name at the time, though I'll concede that this project isn't simply "enhanced" (subjective term) PDCurses. I have no personal stake in one name or another, and will be content with whatever is decided on, but thought that the naming issue in general needed to be raised.

@Bill-Gray and @GitMensch: It appears that Bill would simply have to go to the repository's "Settings" tab and rename the repository from there. I just did that with my "fork" of this project as a test: https://github.com/loblolly986/PDCurses-test. This did not break my existing pull requests, and (at least for now) the previous https://github.com/loblolly986/PDCurses (and sub-paths) automatically redirects to the new name. It also does not break the "fork" status; if removing that would be desired here, doing it the proper way apparently would mean contacting GitHub support. One could create a "mirror" repository on GitHub to do it themselves as described [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository), but GitHub-specific data (not part of the Git repository per se) such as issues and pull requests would not be carried over, which is obviously undesirable here.

By the way, there are some additional fixes and improvements to WinGUI that I intend to submit here, so don't publish a new release *just* yet... :-)

**Comment by GitMensch** [comment]
@loblolly986 thanks for the rename hint. @Bill-Gray can you please do this when you see the time and also drop a not to GH support asking for removing the fork status?
Again @loblolly986 : I don't see this one as BG-PDCurses, while he definitely started it and put the most work in there where a multitude of contributors, including 2 of the 4 new ports and most of the CI environment. If - at all - I'd name it CommonPDCurses but I like a shorter one like PDCursesC more and PDCursesX sound better.

**Comment by loblolly986** [comment]
A few other ideas that have come to mind: "PDCursesA", "PDCurses-A" or "-AE" (for "alternative edition"); "PDCurses CE" ("custom edition"); or "PDCursesM", "PDCurses-M", or "-ME" ("modified edition"). Or even "PDCursesMod" (following the example of such projects as VirtualDubMod and AvsPmod). Just throwing these out there.

Personally, I'd favor a short suffix that stands for some relevant meaning. "PDCursesX", if anything, could come across as an alternative form of "Ex", which has already been objected to for understandable reasons. But again, I'll be fine with whatever y'all decide upon.

**Comment by GitMensch** [comment]
I'd argue against "A" as it has the "ansi vs. unicode" taste in win32 land.
PDCursesMod sounds fine to me and has definitely more meaning than PDCursesX, also can't be confused with "X11" or "eXtended" :-)

**Comment by Bill-Gray** [comment]
Agreed on not liking BG-(name)... I _didn't_ actually put the most work into it;  the various people who originally worked on PDCurses have a sizable lead on the rest of us put together.  Some may not like the direction we've gone in,  but the fact remains that we're standing on their shoulders;  the name should reflect that.

There's also a practical aspect to this : I don't want people looking at the "BG" and assuming it's a one-person project.  In the last few months,  we have benefitted from the addition of DOSVGA from @chasonr, WinGUI enhancements from @loblolly986, the new Plan9 platform from @staalmannen,  fixes for automated builds from @jmalak and @jwinarske,  and a variety of fixes and administration by @GitMensch (the latter being something I am particularly happy about;  I've been quite busy with 'day job' work recently,  and a lot of these improvements probably wouldn't have made it through had Simon not been shepherding things.)

Anyway... a name that doesn't look like a personal project is more likely to get that sort of wider involvement.  I think I'd be good with either PDCursesM ("modified") or PDCursesX ("it's different in an unspecific way").

**Comment by GitMensch** [comment]
@Bill-Gray can you please [contact support](https://support.github.com/contact) to remove fork status of this repository while we wait for the decision about the new name to finish (as we see the name change can be done manually afterwards)?

And for that: PDCursesMod would be better than PDCursesM. While longer, the "Mod"-suffix is quite clear and compares to the samples given by @loblolly986 above - so my personal preference changed to this "longer" name, as "Ex" and "X" are still "similar" and "X"->"XCurses" is also too easy to confuse.

**Comment by loblolly986** [comment]
Funnily enough, when I was writing the suggestions above I didn't like "PDCursesMod" as much, but after thinking about it more, it seemed to carry even better disambiguation power than the others in terms of distinguishing this not just as a variant of PDCurses, but an *unofficial* variant.

Since Simon has requested removing the "fork" status again, I'll add that another feature we'd seemingly gain from having it removed would be the "Contributors" section on the repository root page listing GitHub users with commits in the repository (with a "fork", this information is hidden away under the "Insights" tab). On the one hand, the "fork" status makes the "family heritage" all the more clear, but on the other hand, removing it would enable more GitHub features.

A little additional information about having GitHub Support "detach" a fork is [here](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork). (I think we'd want "forks" of this project to be associated with it and not the upstream project.)

**Comment by staalmannen** [comment]
My 2 0.01€ would be that it would be nice if all alterations to the "curses" name is either prefix or suffix. I think "Mod" is a good and more neutral word than "Ex" which would imply that the BG fork would be better than the official upstream one. Since all other "curses" implementations (ncurses, netbsd-curses) uses prefix, I think this is nicer.

I think it is great with forks and that a project can develop in different directions for mutual benefit an hopefully without animosity. I really like that @Bill-Gray really acknowledges and appreciates all the important and great work done before by @wmcbrine and others.

My suggestion would thus be mPDCurses or MPDCurses (MCurses for short) where M stands for "Mod". I also liked the "Common" as a word suggested by @GitMensch  and CCurses "Common Curses" would also have been a nice name I think.

**Comment by GitMensch** [comment]
Just create the reference:

* the original "fossil pull request": https://github.com/wmcbrine/PDCurses/pull/6
* one of the original suggestions for a possible merge https://github.com/wmcbrine/PDCurses/issues/64

I think we're nearly done here, just waiting for @Bill-Gray to let the fork status be removed and trigger the actual name change.

**Comment by GitMensch** [comment]
We should keep all files under public domain, both to ensure the possibility to exchange code upstream and to not create more confusion by such a difference to upstream. People expect PDCurses (including forks) to be under public domain if there's no big warning up front (at least I'd expect this). Leaving "PDCurses" in the name helps to not think about this as another curses but as a changed PDCurses - which it is.

**Comment by Bill-Gray** [comment]
It sounds if PDCursesMod has wide support,  so I've gone with that.  As noted by @loblolly986, links to Bill-Gray/PDCurses are automatically remapped to Bill-Gray/PDCursesMod.  It all seems to work quite transparently;  I had no real desire to see stuff break as a result of a simple rename.  Thus far,  all I've done is to go into the Settings tab and change the name;  I haven't gone through the repository to do a search-and-replace.

I've also put in a request to GitHub support to detach this fork from @wmcbrine's repository.

The benefits of detaching this fork appear to be limited.  We might get GitHub's search to work properly;  contributors would be listed up-front instead of within an 'insights' tab;  and GitHub would count contributions within this repository (instead of only counting those which are pulled by William).

I really do see this repository as,  in fact,  a fork of upstream PDCurses.  But it's either a major fork (my viewpoint) or a "misfork" (William's view).  Either way,  detachment seems a reasonable step.

**Comment by Bill-Gray** [comment]
...And after a little back-and-forth with GitHub support,  we appear to be "detached".

**Comment by GitMensch** [comment]
There's mainly one important last step: the first release under the new name.
