### ISSUE TITLE
wchgat with "alternate characters"

### ISSUE THREAD

**Issue by rmorales87atx** [Bill-Gray/PDCursesMod#192]
If `wchgat` is called on a line that happens to have "alternate characters", like `ACS_ULCORNER`, the characters become messed up:

![wchgat_before](https://user-images.githubusercontent.com/3020857/98262945-cef36d00-1f4b-11eb-8a85-7be3891d77c3.PNG)

In `attr.c`, around line 348 I adjusted the `for` loop:

```
    for (n = startpos; n <= endpos; n++)
    {
        if ((dest[n] & A_ALTCHARSET))
            dest[n] = (dest[n] & A_CHARTEXT | A_ALTCHARSET) | newattr;
        else
            dest[n] = (dest[n] & A_CHARTEXT) | newattr;
    }
```

This now produces the "expected" output:

![wchgat_after](https://user-images.githubusercontent.com/3020857/98262957-d1ee5d80-1f4b-11eb-9e29-96434f45e9af.PNG)

I observed the same "buggy" behavior with `wchgat` in ncurses.

**Comment by Bill-Gray** [comment]
Thank you.  Just looking at the code,  that makes sense.  I _think_ the `for` loop could read
```
    for (n = startpos; n <= endpos; n++)
        dest[n] = (dest[n] & (A_CHARTEXT | A_ALTCHARSET)) | newattr;
```
I'm currently running in six directions at once,  so it may be a few days before I investigate,  fix,  test,  and push the fix.

It also looks as if @wmcbrine's version has the same issue,  so I'm assuming he'd want a heads-up on this.

I've not seen a mention of this on the `ncurses` bug list;  do you know if Thomas Dickey knows of this bug?  If not,  I'll put a message there.

**Comment by rmorales87atx** [comment]
> I've not seen a mention of this on the `ncurses` bug list; do you know if Thomas Dickey knows of this bug? If not, I'll put a message there.

I did a cursory Google search with "ncurses wchgat alternate" and didn't come up with anything.

**Comment by wmcbrine** [comment]
I can see why this behavior would be thought undesirable, but I'd hesitate to call it a "bug". A_ALTCHARSET is an attribute (isn't it?); wchgat() replaces all the attributes. Maybe A_ALTCHARSET should be seen, and treated, in a different way from other attributes? Maybe.

**Comment by Bill-Gray** [comment]
I sort of see what you mean about it being an "attribute".  But I really can't come up with a case where the current behavior would be desirable,  and can think of many situations where it would be undesirable.  (Basically,  any situation where the underlying text has box or other alt-charset text in it,  and you want to keep those characters "as is".  Actually,  if you _did_ want to modify them,  I can't see why you'd want them to change in this particular way;  changing the corners to V, W, X,  and Y makes no real sense.)

**Comment by wmcbrine** [comment]
The thing is, what behavior seems "desirable" isn't the only, or even primary, guide, to me, to what PDCurses should do. I ask, what do other implementations do? What (if any) is the specified behavior? What's historically expected? Most of all -- what will lead to the fewest surprises when porting?

For example, consider start_color(). This function makes a little sense, maybe, in ncurses. It's totally useless in PDCurses. If I were doing a clean implementation, I'd just start PDCurses in color mode. But, if I did that, then people would write a program using color against PDCurses, move to ncurses, and wonder where the color went. Even worse is keypad(). In ncurses, this allows parsing the individual characters that make up a key code, if for some bizarre reason you wanted to do that, and unfortunately that's the default behavior. In PDCurses, it just drops them on the floor, since there were never any escape sequences to begin with. This is a useless mode, and it's the default. But, if I did away with it, then people would write programs that accepted key codes against PDCurses, and wonder why they didn't work with ncurses.

In this case, applying wchgat() to a window in ncurses affects A_ALTCHARSET. If it didn't in PDCurses... surprise!

**Comment by Bill-Gray** [comment]
@wmcbrine All true.  I'm not going to rush to "fix" this.

I've posted [this message on the `bug-ncurses` list](https://lists.gnu.org/archive/html/bug-ncurses/2020-11/msg00000.html) in hopes of getting some more info.  I strongly suspect this isn't what was intended in the original specification,  and if somebody had thought of it,  they'd have made it clear that `A_ALTCHARSET` should be left alone by `wchgat()`.  But as you point out,  it may be that "everybody's doing it",  and we really can't break several decades of behavior.  Even when it's actually misbehavior.

**Comment by Bill-Gray** [comment]
From the `bug_ncurses` discussion,  [nothing in the specification comes right out and says we couldn't 'fix' this](https://lists.gnu.org/archive/html/bug-ncurses/2020-11/msg00002.html).  However,  every other known implementation has this (admittedly pointless) behavior.  That's a lot of precedent to overturn,  and I'm not enthusiastic about us being the outlier.  So I think we're stuck with this strangeness.

**Comment by GitMensch** [comment]
Maybe reopen and adjust the docs to hint about that and/or add a note in the code?
