### ISSUE TITLE
PDCurses/WinGUI MSYS2

### ISSUE THREAD

**Issue by A2va** [Bill-Gray/PDCursesMod#196]
I have installed PDCurses with the MSYS2 environnement. Basic function like printw are worked but if i use newwin or subwin the function return a structure who all field are blank. And if I set a field of the struct I got a Segmentation Fault error.
```c
#include <pdcurses.h>
int main()
{
	initscr();
	WINDOW *win = subwin(stdscr,50, 10, 10, 10);
	win->_begx=10;
	wrefresh(win);	
	endwin();
	return 0;
}
```

**Comment by Bill-Gray** [comment]
Problem seems to be that you're making a window starting on line 10 and extending 50 lines.  This will not fit within `stdscr` unless the screen is at least 60 lines high. (Perhaps you wanted something 50 _columns_ wide and ten high?  The fact that most PDCurses/curses functions work in yx order instead of xy still trips me up at times...)

 [If the requested subwindow doesn't fit within the "original" window,  `subwin` returns `NULL`.](https://github.com/Bill-Gray/PDCursesMod/blob/663561ceac3b873d7607498c7683e9c0048a64c0/pdcurses/window.c#L303)  There have been various times where I've actually wanted a subwindow to go off-screen,  much as one can drag a window in a GUI partly off-screen.  But you can't do that.

I compiled your code with the VT flavor,  changing `pdcurses.h` to `curses.h` and adding in an `assert( win);` line.  With that flavor (and in WinCon),  the screen size is set by the initial size of the terminal within which the program is running.  If I make that terminal 60 lines high and run your program,  it works.  In a 59-line terminal,  the `assert` stops the program.

**Comment by A2va** [comment]
Thanks for your explaination ! After modification of the code it actually works.
