### ISSUE TITLE
What is WinGui?

### ISSUE THREAD

**Issue by untyper** [Bill-Gray/PDCursesMod#201]
How does it differ from the regular wincon? Is the api the same?

**Comment by GitMensch** [comment]
Yes, the API is the same (as this is what makes PDCurses PDCurses). There are some functions in PDCurses that are ignored in some ports like `PDC_set_title`, but the API is always identical.

The main difference of the WinGUI port is that it uses a win32 native GUI, window so you can (but don't have to) use `WinMain` instead of a plain `main` which is commonly used to create console applications and always have an own GUI window (with min/max/resize/title/font-choosing).
WinGUI also has better support for different attributes and wide-character.

Just a note: there's another option, too, the VT port. This uses a different set of internal codes and possibly also works better outside of plain "cmd.exe" (console in Windows Terminal, PowerShell and tools like vscode come to mind).
