### ISSUE TITLE
Was for variable `rval` in function `running_under_wine` the storage intended to be static?

### ISSUE THREAD

**Issue by bernhardu** [Bill-Gray/PDCursesMod#219]
Hello Bill-Gray,
was for variable `rval` in function `running_under_wine` the storage intended to be static?
It looks like this check should be done just once per process, but currently it seems to take always the GetProcAddress path.

https://github.com/Bill-Gray/PDCursesMod/blob/c96ad5deb78bc66dc4792195c8fcaafd645e8ce1/wincon/pdckbd.c#L445-L457

(I was just looking through the wine bug tracker when I came to this [guide issue](https://bugs.winehq.org/show_bug.cgi?id=51883), but unable to find enough download from projectpluto.com to reproduce the issue, I wasn't sure if or how I should get in contact, I looked further to find other references to this software, which led me to this unrelated [PDCursesMod issue](https://bugs.winehq.org/show_bug.cgi?id=51558) which led me to your github repository, where I found a few wine related commits ... while I just wanted to make you aware of these bugs, while even not sure how "real" they are ...)

**Comment by Bill-Gray** [comment]
You are correct.  `rval` ought to be static.  It does work despite that,  and the performance hit would be tiny.  It simply results in `GetModuleHandle()` and `GetProcAddress()` getting called for most keyboard input,  instead of just getting called once and the result being kept.

But it does "look wrong";  anybody looking at it (except me,  until you pointed it out) will wonder why the code is pointlessly setting the value,  then checking to see if it it's equal to that value.

Thanks for pointing this out.  I've just fixed it.

The issue with Guide is interesting.  I'm no longer actively developing that software,  but it's worked on every version of Wine I've tried... but the latest version I have is 6.0.2,  and Tom reports issues with 6.18.  I'll probably have to investigate,  and register to comment on WineHQ's Bugzilla.

The 'unrelated PDCursesMod issue' (WinCon doesn't work in Wine) is known to me.  WinCon has gradually gotten better under Wine over the years;  this has more to do with Wine improving than WinCon.  But there are still rough edges.  WinGUI works without issues on Wine,  and has done so for (I think) about ten years.

**Comment by GitMensch** [comment]
Fixed with 763d9de,

**Comment by GitMensch** [comment]
> The 'unrelated PDCursesMod issue' (WinCon doesn't work in Wine) is known to me.

Is this "not-our-bug" or something that can be fixed on the WinCon side? If it can be fixed then it would be good to have a "real issue" created for that part.

**Comment by bernhardu** [comment]
Thanks for the immediate responses. 

> Tom reports issues with 6.18

One thing to add here is, he is using wine-staging. It might be limited to that branch.
But I am sorry not being of better help without the right CD.
(@Bill-Gray Is the update zip from 8.0 to 9.0 still available for download?)

> PDCursesMod

Unfortunately Vladimir left out the details what was not working, but the last comments in the bug pointing to missing functionality at wine side.
