### ISSUE TITLE
KEY_RESIZE is not received when expected

### ISSUE THREAD

**Issue by Lyle-Tafoya** [Bill-Gray/PDCursesMod#230]
The most  common scenario in which I am used to receiving KEY_RESIZE events in ncurses is when a user resizes their terminal emulator window or when they change the font size (which many terminal emulators allow to be done with a convenient keyboard shortcut). The following code works on Linux with ncurses for detecting such events (in every terminal emulator I have tested so far):
```c
#include <curses.h>

int main()
{
  initscr();
  noecho();
  cbreak();

  for(int input = getch(); input != 'Q'; input = getch())
    if(input == KEY_RESIZE)
      addstr("KEY_RESIZE");

  endwin();
}
```
However, when I use PDCursesMod, I cannot find any way to trigger KEY_RESIZE. I tested this with wincon, sdl2, and wingui on Windows and I tested it with vt and sdl2 on Linux. When using wingui, the window did not appear to be resizable by the window manager during runtime, and so that test didn't work. With sdl2, wincon, and vt builds, the window can be resized, but the resize event does not seem to be detected.

I also did another test where I checked the values of COLS and LINES (which typically have changed values after a KEY_RESIZE in ncurses) every iteration of the loop to see if maybe they were being updated despite the lack of KEY_RESIZE. They were not being updated and still reported the same values as were present when the program was initialized.

I'm not sure where this is expected to work (ie. do windows console programs even have the capability to detect resize events?) but I did see some older discussions in the issue tracker about KEY_RESIZE, so I assume it's expected to work in some environments.

**Comment by Bill-Gray** [comment]
I hadn't run into this,  because just about all of my programs use "special" keys (function, and cursor keys and so forth) and therefore call `keypad( stdscr, 1)`.  With ncurses,  if you don't do that,  hitting (say) F3 will get you a string of control characters;  if you do it,  you'll get `KEY_F3`.  And similarly for arrow keys and so forth.

In PDCurses and PDCursesMod,  pressing arrow and cursor keys defaults to producing nothing.  Call `keypad( stdscr, 1)`  and you get `KEY_F3`, `KEY_LEFT`,  etc.

It appears that both PDCurses and PDCursesMod consider `KEY_RESIZE` to be "special",  and it's therefore suppressed by default.

If you compile the program below with PDCurses or PDCursesMod,  and run it with at least one command-line argument,  "special" keys (including `KEY_RESIZE`) will be processed and shown.  Run without command-line arguments,  "special" keys won't be processed;  hit F3 or resize the window,  and nothing happens.

I can come up with no good reason not to call `keypad( stdscr, 1)`.  As I say,  it's a standard thing in my programs;  without it,  hitting a special key in ncurses results in an escape sequence,  and it's easier for me to ignore `KEY_F3` than it is to parse escape sequences.  If it weren't for the weight of forty-odd years of existing code,  we'd probably switch the default to having `keypad` always be true.

But we _do_ have that weight.  I lean toward the ncurses solution of having `KEY_RESIZE` returned whether you've called `keypad( stdscr, 1)` or not,  but hope @wmcbrine can offer an opinion on this?

Two other comments : 
- programs that handle resizing have to call `resize( 0, 0)` after receiving a `KEY_RESIZE`,  as shown in the code below.  (Though interestingly,  I see that ncurses doesn't require this,  and I don't know _why_ it's required in PDCurses/PDCursesMod.)
- By default,  WinGUI windows are not resizable.  I ran into issues some time back with legacy programs that didn't expect windows to be resizable and couldn't handle it well when it did happen.  But you can [set WinGUI windows to be resizable](https://projectpluto.com/win32a.htm#user_resizing_fix),  and even set the range of possible sizes.

This does cause me to notice the extent to which resizability in PDCursesMod is platform-dependent,  which doesn't seem like a good idea.
```c
#include <curses.h>

int main( const int argc, const char **argv)
{
  initscr();
  noecho();
  cbreak();
  if( argc > 1)
     keypad( stdscr, 1);

  for(int input = getch(); input != 'Q'; input = getch())
    if(input == KEY_RESIZE)
    {
    resize_term( 0, 0);
      addstr("KEY_RESIZE ");
    }
    else
    {
      addstr( keyname( input));
      addch( ' ');
    }
  endwin();
}
```

**Comment by GitMensch** [comment]
I _guess_ that `resize(0,0)` is mandatory because "back in times" you'd be possibly either flooded by events when resizing and/or you wouldn't get the last actual resize event in any case.

I'd prefer to not need that call - especially if ncurses doesn't need that.
I'd also prefer to always return `KEY_RESIZE`, _if_ ncurses does this without a call to `keypad()`.

**Comment by Bill-Gray** [comment]
Still testing,  but it looks as `KEY_RESIZE` is returned even when not in keypad mode by the simple expedient of modifying [this line](https://github.com/Bill-Gray/PDCursesMod/blob/ab8b038dc973f61be80e89d744d0f895aded3996/pdcurses/getch.c#L506) to read
```c
if( key != KEY_RESIZE && PDC_is_function_key( key) && !win->_use_keypad)
```
(i.e., "filter special keys if not in keypad mode,  with the exception of `KEY_RESIZE`".)

I've also modified `wgetch()` in the same file to say "if we're about to return `KEY_RESIZE`,  call `resize_term(0,0)` first".  That appears to remove the need to call `resize_term(0,0)` ourselves (for example,  in the above programlets).  You can [click here to see the modified `getch.c`](https://www.projectpluto.com/temp/getch.c).

This works in the testing I've done for the VT,  X11,  SDL2,  WinGUI,  VT,  and Linux framebuffer ports.   You can still do a redundant call to `resize_term(0,0)` without trouble.

As I think it through,  I'm not so concerned that this will break existing behavior.  The "existing behavior" in the first case was that you'd get bizarre,  undefined stuff happening if the window was resized in non-keypad mode.  And in the second case,  if you failed to call `resize_term(0,0)`,  the behavior was (as far as I can see) undefined.  So I am shifting from "is this the right thing to do" to "let's make it work".

**Comment by Lyle-Tafoya** [comment]
In my limited testing, I find your changes to work as expected in wincon, wingui, and sdl2 on Windows as well as vt and sdl2 on Linux.
