### ISSUE TITLE
Resizing window after terminal resize crashes

### ISSUE THREAD

**Issue by pavkam** [Bill-Gray/PDCursesMod#266]
# Background
Compiled with `make CLANG=Y WIDE=Y DLL=Y CHTYPE_32=Y` on latest MacOS ARM64.
Creating a window on the screen with (1, 1, width -1, height -1) in which text is written.

# Situation
- When resizing the terminal, and the cursor position is *not* on the last line, everything works as expected.
- When the cursor is on the last line in the window, and the screen is resized, an error occurs.
- Reducing or increasing the terminal's size results in the same error so it's not a "space" issue.

# Error
```
sharpie-demos-events(61265,0x1f0f72500) malloc: *** error for object 0x13c00daa0: pointer being freed was not allocated
sharpie-demos-events(61265,0x1f0f72500) malloc: *** set a breakpoint in malloc_error_break to debug 
```
![Untitled](https://user-images.githubusercontent.com/7327309/210537789-dca11ebe-2098-4608-abe5-e10e404931bf.gif)

**Comment by Bill-Gray** [comment]
Hmmm... quite a few programs (including a lot of mine) fill the screen with text and leave the cursor in the last row.  It's a _very_ common setup,  and resizing occurs in such cases without trouble.  I think there may be another ingredient to this crash.  Can you post source for a minimal example of this bug?

**Comment by pavkam** [comment]
My case has a window on top of the screen. The borders in the GIF are drawn on the Screen while the contents inside are on another Window. I also use a dummy Pad to listen for key events on `wget_wch`.

My library was built on top of NCurses and I am adding support for PDCursesMod as an option. 

I will try to reduce the example to just Curses API calls (at the moment there's a layer of abstraction between the example and the library itself).

Thanks,
Alex.

**Comment by pavkam** [comment]
Update: same error on Windows ARM64 (sorry, have no access to x64 hardware)

**Comment by pavkam** [comment]
I have narrowed it down to `scrollok` being on in the window. On resize, if the window has been scrolled, and a line is removed from the back, it explodes.

Here is the smallest example I could come up with that shows this. It's not C/C++ but it uses the same primitives from Curses:
```csharp

var screenHandle = c.initscr();

var handle = c.newwin(c.getmaxy(screenHandle) - 2, c.getmaxx(screenHandle) - 2, 1, 1);
c.scrollok(handle, true);
c.wtimeout(handle, 50);

c.wmove(handle, c.getmaxy(handle) - 1, 0);
c.setcchar(out var ch, "A", VideoAttribute.Bold, 0, IntPtr.Zero);
c.wadd_wch(handle, ch);
c.setcchar(out ch, "\n", VideoAttribute.Bold, 0, IntPtr.Zero);
c.wadd_wch(handle, ch);

c.wrefresh(handle);

while (true)
{
    var res = c.wget_wch(handle, out var key);
    if (res == -1)
    {
        continue;
    }

    if (res == (int) PdCursesKeyCode.Yes + 0xeb00 && key == (int) PdCursesKeyCode.Resize + 0xeb00)
    {
        c.wresize(handle, c.getmaxy(screenHandle) - 2, c.getmaxx(screenHandle) - 2);
    }
}
```

**Comment by Bill-Gray** [comment]
Hmmm... there are some odd things going on in there,  but for starters,  why the "mystery constant" `0xeb00`?  To what does that refer?

It looks as if you're saying "if we get a `KEY_RESIZE` event,  resize the window."  Why would you do this?  (Offhand,  I think it'll cause yet another resize and will probably cause a crash.)

I'd think also that the check for `res == -1` is redundant.  In such a case,  you'll "continue" anyway and won't execute the following statements in the loop.

**Comment by okbob** [comment]
pá 6. 1. 2023 v 19:38 odesílatel Bill Gray ***@***.***>
napsal:

> Hmmm... there are some odd things going on in there, but for starters, why
> the "mystery constant" 0xeb00? To what does that refer?
>
> It looks as if you're saying "if we get a KEY_RESIZE event, resize the
> window." Why would you do this? (Offhand, I think it'll cause yet another
> resize and will probably cause a crash.)
>
Maybe I don't understand this point, but it looks like a valid pattern -
probably only stdscr can be implicitly resized. Otherwise other windows
should be resized by application when KEY_RESIZE is processed (some windows
should be fixed, some can be resized). ncurses has some strange heuristics.
When the window is over a visible screen or near border, then it is resized
implicitly, and it is probably one of worse ncurses features in my list.

**Comment by Bill-Gray** [comment]
@okbob - ah,  yes,  I see what you mean... I'd misread that chunk of the code.

I've [produced a C version of the above code](https://www.projectpluto.com/temp/iss266.c) and I think I see what's going here,  and should be able to fix it.  (gdb and valgrind both point to the same line of code,  and I think I see how scrolling might mess up that code's intended purpose in life.)

**Comment by Bill-Gray** [comment]
@pavkam,  thanks for the bug report.  I've duplicated the problem and pushed a fix (commit 72521a1697ecc431553fdeb3)... give it a try.  Details for the curious :

It used to be that windows were allocated as an array of `height * sizeof( chtype *)` pointers to lines,  and then we did an allocation of `width * sizeof( chtype)` bytes for each line.  It meant a fair bit of extra code to handle memory failures and window allocation/deallocation.  Scrolling just involved cycling the pointers.  They'd get freed in a different order than they were allocated (if scrolling happened),  but that wasn't a problem.

I revised things so we just allocated one buffer of size `width * height * sizeof( chtype)` bytes,  and set pointers within that buffer.  All well and good,  but now the cycling of pointers in `wscrl()` meant we'd free a pointer that wasn't the one originally allocated.

So now,  the code moves the actual characters instead of pointers to the characters.

This proved to be relatively easy,  except that I messed up my [test routine](https://www.projectpluto.com/temp/iss266.c) and took longer to figure that bit out than should have been the case.

**Comment by pavkam** [comment]
Thanks @Bill-Gray , I will check it out later when I have a chance. 

Kind regards,
Alex

**Comment by pavkam** [comment]
@Bill-Gray -- this case seems to be covered. I found though, that it crashes with a SEGFAULT if there's one window in the middle of the screen and the terminal is resized to remove chink of it. I will try to come up with an example

**Comment by pavkam** [comment]
Found it, my code has anti-NCurses-heuristics protection when it comes to window sizes and would sometimes try to resize the windows automatically. Sometimes the width/height would be negative and that was OK with NCurses (it will return ERR in `wresize`). Looks like PDCursesMod does crash if getting negative width/height. 

Probably a quick fix will be to check for negative values and return ERR instead of crashing.

(I have adjusted my code as well to not call `wresize` in these cases).

**Comment by Bill-Gray** [comment]
@pavkam - thank you.  As you wrote,  this is an easy one to fix.  The only slight issue was that `newwin()`,`subwin()`,  `resize_window()`,  and some others  interpret `nlines==0` or `ncols==0` to mean "full width" or "full height".  So in some of the functions,  we have to check for positive values;  in others,  for non-negative values.  That wasn't much of a problem,  though.

@wmcbrine may be interested in this;  PDCurses has the same bug (and can be fixed with similar ease).

**Comment by pavkam** [comment]
All good here, @Bill-Gray, think you can close those ticket.
