### ISSUE TITLE
wincon/wingui: How to output "extended/encoded" codepage values 0x01-0x1F

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#313]
This issue is the reverse of #209 and possible its related #245.

Issue at hand:

`putc(0x1E)` displays a small triangle with the tip pointing upwards, when in chcp 437
![grafik](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/c18627de-3a6a-47f1-bc45-bf4db64970e7)

Doing the same with `addch(0x1E)` doesn't:
![grafik](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/efce00ec-e368-41f8-acf3-a22026b5bc0c)

Note: this is a build with version 4.3.7 (CHTYPE=64, WIDE=0, UTF8=0 PDCursesMod for Windows).

Also: the original request come from @eugeniodilo - so CC'ing him here.

Just to make sure @eugeniodilo Can you please check if there's a different output when renaming pdcurses_wingui.dll in your used package under "bin" to pdcurses.dll (replacing the wincon one)?

**Comment by eugeniodilo** [comment]
pdcurses_wingui.dll  renamed to pdcurses.dll .
screenshot is attached . nothing is changed
thx

Il giorno lun 22 gen 2024 alle ore 15:30 Simon Sobisch <
***@***.***> ha scritto:

**Comment by GitMensch** [comment]
The mail system on GH does not attach anything (norv uses formatting), please post directly.

**Comment by Bill-Gray** [comment]
Replicated using the test code below.  It happens on PDCurses, PDCursesMod, and on ncurses.  I think this translation is the expected behavior for Curses (I've never seen it work any other way).

PDCurses (and therefore PDCursesMod) offers a `raw_output()` function,  used below,  to disable this behavior.  At least at first glance (minimally tested thus far,  in the VT port on PDCursesMod and the X11 and SDL2 ports on PDCurses),  it does that on certain ports and not others.  SDL2 and WinGUI worked;  I don't think X11 had those characters in the font;   VT and WinCon didn't,  though the latter was in Wineconsole and is not a totally excellent test.

Note that I turned `raw_output( TRUE);` while emitting those characters,  and shut it off afterward.  Leaving it on means that (for example) the `\n` characters in the various `printw()`s are not translated and don't move you to the beginning of the next line.

Also,  it _is_ specific to PDCurses*.  I don't know of a method that's portable to ncurses and/or other implementations.  If you're on a Unicode platform,  you can emit U+25B2 for an upward-pointing arrow (as shown below);  that _will_ work on ncurses and elsewhere.  (Other than for compatibility with ancient code,  I can't think of a good reason to use 8-bit character sets in 2024.  Unicode is awesome.  Of course,  legacy code is part of PDCurses' raison d'être.)
```c
#include <curses.h>

int main( void)
{
   initscr();
   noecho();
   cbreak();
   printw( "0x1d, 0x1e 'normally' : ");
   addch( 0x1d);
   addch( 0x1e);
#ifdef __PDCURSES__
   printw( "\n0x1d, 0x1e in raw output mode : ");
   raw_output( TRUE);
   addch( 0x1d);
   addch( 0x1e);
   raw_output( FALSE);
#endif
#ifdef WACS_S1
   printw( "\nUpward-pointing triangle as U+25B2 : ");
   {
      cchar_t c = (wchar_t)0x25b2;

      add_wch( &c);
   }
#endif
   printw( "\nHit a key :");
   getch( );
   endwin();
   return( 0);
}
```

**Comment by GitMensch** [comment]
Are there specific values which would have to be output as raw or does this depend on something complex?

**Comment by Bill-Gray** [comment]
Not sure what you mean here?

Translation is done,  by default,  for characters 0-31 and for 0x7f :

https://github.com/Bill-Gray/PDCursesMod/blob/45949000c3ac1375f5f821d72f46e4726a3a6a2f/pdcurses/addch.c#L556

   "Normally" (i.e.,  unless you call `raw_output( TRUE);`),  `addch()` will backspace when fed a backspace,  carriage-return/line-feed when fed a `\n`,  and output `^(character)` for most other control characters (see the `/* handle control chars */` bit a few dozen lines below the above link.)

**Comment by GitMensch** [comment]
Do you know if this range also applies to ncurses (or know about the part in the code that does the translation there)?

**Comment by Bill-Gray** [comment]
The 'normal' behavior,  in which you get a backspace when you backspace,  a carriage return/line feed with a `\n`,  etc.,  is indeed what happens in ncurses (and,  I believe,  other implementations of curses).  So we're doing the "right",  specified thing there.

The `raw_output()` function applies _only_ to PDCurses and PDCursesMod,  and to no other curses implementation.  In that mode,  the behavior appears to be correct as well (on the platforms where that function has any meaning).

So I think we're good on this one (i.e.,  the "bug" is actually "the specified behavior"),  and am closing this as "wasn't actually a bug".  (Or would so close it if GitHub offered that as an option.)
