### ISSUE TITLE
changed attributes applies to already processed text

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#76]
Given the following scenario:

* output a hidden string at first line with black foreground on a black background
* output descriptive text afterwards (default attributes)

everything is fine:

![grafik](https://user-images.githubusercontent.com/6699539/32138719-04318044-bc38-11e7-8a0c-d13f25e61092.png)

* output another string at second line with different colors
* output descriptive text afterwards (default attributes)

the result with pdcurses (both win32 [3.4 and 4.0.2] and win32a) is:

![grafik](https://user-images.githubusercontent.com/6699539/32138723-10aeb5f8-bc38-11e7-8e85-6128fbb6e913.png)

--> the color attributes of the second line are applied to both the first and the second line, making the first line readable

Expected result is the one given when run with ncursesw (checked 6.0): the first line stays unchanged.

Is this "by design" or a defect (either in PDCurses code or in the library using PDCurses)?

**Comment by GitMensch** [comment]
ping @Bill-Gray  - do you see any chance to investigate this issue?

**Comment by wmcbrine** [comment]
A code example might be helpful.

It's the intended behavior in PDCurses that changing the colors of an existing color pair (assuming that's what you're doing), changes the rendering of everything already using that color pair. I had thought that ncurses did the same...

**Comment by Bill-Gray** [comment]
The new `init_col` demo in PDCursesMod does this sort of thing,  drawing text with a given color pair and then resetting the colors.  The result is that,  as William says,  all text using that pair gets redrawn,  in PDCursesMod and in ncurses.

I think this goes back to the days of hardware color palettes,  where you really couldn't avoid text being redrawn in the newly selected colors.  So yes,  it's intentional behavior.
